version: '3'

x-database-variables: &database-variables
  spring.liquibase.enabled: 'true'
  spring.application.name: 'java-backend'
  spring.datasource.username: postgres_user
  spring.datasource.password: postgres_password
  spring.datasource.drive-class-name: org.postgresql.Driver
  spring.datasource.url: jdbc:postgresql://database:5432/postgres_database
  spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect
  spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  spring.jpa.hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  spring.jpa.hibernate.ddl-auto: none
  spring.sql.init.mode: always
  spring.jpa.generate-ddl: 'true'
  spring-server-port: 5000


services:
  react_frontend: 
    container_name: react_frontend 
    build:
      context: ./warehouse-frontend 
      dockerfile: Dockerfile
      args: 
        REACT_APP_API_BASE_URL: http://localhost:8080
    ports:
      - 3000:3000

  java_backend:
    image: 'docker-spring-boot-postgres:1.0.0'
    build:
      context: ./warehouse-backend
      dockerfile: Dockerfile
    container_name: java_backend
    ports:
      - 8080:8080
    environment:
      <<: *database-variables
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h database -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
    #- SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres_database

  database:
    image: "postgres:13-alpine"
    container_name: postgres_container
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres_database
    #env_file:
    # - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data: # named volumes can be managed easier using docker-compose
